server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    consul:
      host: consul-server1
      port: 8500
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka/


