spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    consul:
      host: consul-server-client
      port: 8500
    config:
      discovery:
        serviceId: customer
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
